"""Deterministic, family-level, country-stratified train/tuning/holdout splits.

Assignment is a pure function of (seed, family_id) — never of row order or
random.seed() state — so the same split can be regenerated byte-for-byte later
and its fingerprint can be checked instead of re-derived. The final holdout is
sealed: callers must not call tuning-metric code on it before an explicit
final-evaluation event (see docs/IMPLEMENTATION_SPEC.md Phase 1/5).
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

TRAIN = "train"
TUNING = "tuning"
HOLDOUT = "holdout"


def _stable_unit_interval(seed: int, family_id: str) -> float:
    """Deterministic pseudo-random value in [0, 1) for (seed, family_id)."""
    digest = hashlib.sha256(f"{seed}:{family_id}".encode("utf-8")).digest()
    as_int = int.from_bytes(digest[:8], "big")
    return as_int / 2**64


@dataclass(frozen=True)
class SplitConfig:
    seed: int = 42
    train_frac: float = 0.8
    tuning_frac: float = 0.1
    holdout_frac: float = 0.1

    def __post_init__(self) -> None:
        total = self.train_frac + self.tuning_frac + self.holdout_frac
        if abs(total - 1.0) > 1e-9:
            raise ValueError(f"split fractions must sum to 1.0, got {total}")


def assign_splits(
    family_country: dict[str, str], config: SplitConfig = SplitConfig()
) -> dict[str, str]:
    """Return ``{family_id: "train"|"tuning"|"holdout"}``.

    Stratified by country: families are grouped by their S1 entity's country,
    then within each country group deterministically ranked by
    ``_stable_unit_interval`` and cut at the configured fractions. This keeps
    per-country split proportions close to the target fractions even though
    country group sizes vary (e.g. India-heavy vs. US-heavy).
    """
    by_country: dict[str, list[str]] = {}
    for family_id, country in family_country.items():
        by_country.setdefault(country, []).append(family_id)

    assignment: dict[str, str] = {}
    for country, family_ids in by_country.items():
        ranked = sorted(
            family_ids, key=lambda fid: _stable_unit_interval(config.seed, fid)
        )
        n = len(ranked)
        n_train = round(n * config.train_frac)
        n_tuning = round(n * config.tuning_frac)
        n_train = min(n_train, n)
        n_tuning = min(n_tuning, n - n_train)
        for i, family_id in enumerate(ranked):
            if i < n_train:
                assignment[family_id] = TRAIN
            elif i < n_train + n_tuning:
                assignment[family_id] = TUNING
            else:
                assignment[family_id] = HOLDOUT
    return assignment


def split_fingerprint(assignment: dict[str, str]) -> str:
    """Stable hash of the full split membership, independent of dict order."""
    payload = "\n".join(f"{fid}\t{split}" for fid, split in sorted(assignment.items()))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def split_counts(assignment: dict[str, str]) -> dict[str, int]:
    counts = {TRAIN: 0, TUNING: 0, HOLDOUT: 0}
    for split in assignment.values():
        counts[split] += 1
    return counts


def save_split_manifest(
    assignment: dict[str, str], config: SplitConfig, out_path: str
) -> None:
    payload = {
        "config": {
            "seed": config.seed,
            "train_frac": config.train_frac,
            "tuning_frac": config.tuning_frac,
            "holdout_frac": config.holdout_frac,
        },
        "fingerprint": split_fingerprint(assignment),
        "counts": split_counts(assignment),
        "assignment": assignment,
    }
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2, sort_keys=True)
